### ISSUE TITLE
Aggregagor endpoint links are broken in the docs

### ISSUE THREAD

**Issue by v0d1ch** [input-output-hk/mithril#1004]
## Steps to reproduce

If you visit https://mithril.network/doc/manual/getting-started/bootstrap-cardano-node, click on _Aggregator endpoint_ for both preview and preprod networks you will see that the links are broken resulting in 404 http error.

**Comment by jpraynaud** [comment]
The endpoint provided in this guide is a prefix: the Mithril client will append the correct path to this prefix depending on the command called and according to our OpenAPI specification.

Here are some resources you may find useful:
- **OpenAPI specification**: https://mithril.network/doc/aggregator-api/
- **OpenAPI playground**: https://mithril.network/openapi-ui/
- **Mithril Explorer**: https://mithril.network/explorer?aggregator=https%3A%2F%2Faggregator.release-preprod.api.mithril.network%2Faggregator

If you have troubles while using this guide, feel free to ask support on our discord channel: https://discord.gg/5kaErDKDRq
