### ISSUE TITLE
Shared library error in CI binaries

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1073]
## Issue
A SPO receives this error message with new binaries pre-compiled in [`2329.0-pre`](https://github.com/input-output-hk/mithril/releases/tag/2329.0-pre):
`./mithril-signer: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

They don't have the problem:
- with the previous versions of the builds
- when they build form sources

Current Linux Version with problem: `Ubuntu 22.04.2 LTS`

**Comment by Alenar** [comment]
Got a confirmation from a SPO that it's indeed working 🥇, he was able to run `mithril-signer --version` without issue.
