### ISSUE TITLE
Make client download and extract the archive simultaneously

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1115]
## Issue
A SPO proposes that the Mithril client downloads the archive and extracts it at the same time:
- This will accelerate the process
- This will reduce the need for storing the compressed archive

See these Discord posts:
- https://discord.com/channels/826816523368005654/1014019542504185876/1135249995176628276
- https://discord.com/channels/826816523368005654/1014019542504185876/1135285017258508298

## Question
Is it possible to stream this way with `zstandard`? See #876

**Comment by intertreeJK** [comment]
I second this emotion, after running into the too much space taken up issue while trying to download the Mithril Snapshot for a newly spun up Node myself.
