### ISSUE TITLE
Create a test network on `SanchoNet`

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1173]
## Why
In order to get ready for the next release of Cardano, we want to make sure that Mithril works properly on the new `Sanchonet` network.

## What
Create a `testing-sanchonet` network.

## How

- [x] Terraform deployment (Cardano conf)
- [x] CI/CD
- [x] GitHub Actions
- [x] Documentation
- [x] Explorer
- [x] Grafana
- [x] Status page
- [x] Eras setup
- [x] SPO setup
  - [x] Create SPO
  - [x] Wait 2 epochs for SPO to being registered  in Mithril
  - [x] Genesis the network 
- [x] Network configuration in infra
- [x] Rotate doc for new network configuration
- [x] Wait for the network to sign first certificate
- [x] Dev blog post
- [x] Make Discord announcement
- [x] Secrets in vault

**Comment by abailly-iohk** [comment]
It would also be interesting to liaise with the responsible team (@disassembler ?) to see whether or not it would be interesting to use Mithril on this particular network as a source of truth for governance status.

**Comment by ch1bo** [comment]
It will also be the next network to fork into a new era (likely some 2-3 months before the actual mainnet fork)

So it's a great testing ground to see how we can support the next era and work through hard fork events.

**Comment by TrevorBenson** [comment]
Is there any status update available for Mithril on Sanchonet?

**Comment by jpraynaud** [comment]
> Is there any status update available for Mithril on Sanchonet?

We expect to have the `testing-sanchonet` Mithril network available in December :+1:

**Comment by jpraynaud** [comment]
Filed a bug issue as `PallasChainObserver` is not retrieving the epoch number correctly: https://github.com/txpipe/pallas/issues/347
