### ISSUE TITLE
Allow clients to check and download immutable DB incrementally

### ISSUE THREAD

**Issue by abailly-iohk** [input-output-hk/mithril#1208]
## Why

We know we'll want to provide some way to have mithril snapshots be more incremental, in order to allow clients to download (and verify) only the parts they are missing and are interested in. 

To make what we currently have more useful, having the possibility to download only the immutable files you are missing (and the relevant ledger state), would be great. It would allow eg. a desktop wallet user to sync up their node in minutes, or even seconds, using mithril.

## What

* Archive and serve each immutable file independently (or as a range)
* Sign and certify a Merkle-Tree root of all immutable files' hashes
* Allow mithril-clients to request download of only "missing" immutable files: 
     * The client would request whatever snapshot they are interested in, check the latest immutable file number, compare with what they have locally, and only download the missing parts.
     * This might not be totally trivial as this would imply the client wipes out the volatile and ledger DBs
* When a fragment is retrieved, associate a MT inclusion proof so that the client only have to verify the root certificate once

**Comment by jpraynaud** [comment]
Superseded by #2047
