### ISSUE TITLE
Enhance machine readable logs in client

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1234]
## Why 
The machine readable logs provided by the clients miss some information and consistency.

## What
We need to make small improvements to the machine readable logs of the client:
- Add timestamps in log entries
- Use only one type of case (snake_case only)
- When using verbose mode, the logs are not provided in json format

## How

- [x] Add datetime in log entries
- [x] Use only one snake_case
- [x] When using verbose mode, the logs are display the debug/info logs in json format(*)
- [ ] Inform users of the current `mithril-client-cli` that impacting modifications  have been introduced

(*): How can we propagate the `--json` option to the logger? Maybe it needs too much refactoring, if this is the case a top level `--json-log-format` can be created)

**Comment by dlachaumepalo** [comment]
@michalrus, With the merge of the PR #1400, an impacting modification have been introduced in Mithril client CLI output logs.

This updates the JSON logs for `snapshot download` command progress:
`bytesDownloaded` is now `bytes_downloaded`
`bytesTotal` is now `bytes_total`
`secondsLeft` is now `seconds_left`
`secondsElapsed` is now `seconds_elapsed`

These changes will be effective on `release-preprod` and `release-mainnet` with the release of the next distribution.

**Comment by michalrus** [comment]
@dlachaumepalo thanks for the heads-up :bow:
