### ISSUE TITLE
Icon for website has not been updated 

### ISSUE THREAD

**Issue by abailly-iohk** [input-output-hk/mithril#1287]
The current icon for website is still the old one: 
<img width="141" alt="Screenshot 2023-10-07 at 10 18 40" src="https://github.com/input-output-hk/mithril/assets/79840582/82819e0b-5b6c-42b1-85be-3c48d1a956b0">

**Comment by jpraynaud** [comment]
It looks like it's a cache problem as the [favicon](https://raw.githubusercontent.com/input-output-hk/mithril/main/docs/website/static/img/favicon.ico) has been updated:
![Screenshot from 2023-10-09 09-42-27](https://github.com/input-output-hk/mithril/assets/5566665/b6ab0686-a019-4a2d-a73d-79aad0b07b5b)
