### ISSUE TITLE
Output CLIs logs to `stderr`

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1515]
## Why
We want to have a clear separation between logs and business data in our CLIs. They are currently all written to `stdout`.

## What
Migrate all terminal logs output to `stderr` by default on the CLIs for client, signer and aggregator. This is a breaking change and we need to handle it properly with our users (bump minor version, announce to our users in dev blog post, discord, slack)

## How

- [x] Do we apply this rule to commands that acts as server/daemon (investigate practices on Cardano node/cli, hydra, and rest of the world)?
- [x] Modify the client CLI and handle breaking change
- [x] ~~Modify the signer CLI and handle breaking change~~
- [x] Modify the aggregator CLI and handle breaking change
- [x] ~~Check the impact on the SPO side~~
- [x] ~~Check if infrastructure needs to be updated to gather logs in loki/grafana~~
- [x] Prepare ADR

**Comment by dlachaumepalo** [comment]
Overview of practices:
- Hydra: https://hydra.family/head-protocol/adr/9/
