### ISSUE TITLE
Provide latest immutable file number with certified `Cardano transactions` in client

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1536]
## Why
We want to provide extra information (latest beacon -immutable file number or block number-) along with the certified status of a transaction in the Mithril client. This information should also be signed by the protocol.

## What
In order to guarantee the latest immutable file number or block number value displayed along the verified transactions, we need to make it part of the protocol message signed by Mithril.

## How

- [x] Add the latest signed immutable file number or block number in the protocol message signed
- [x] Include the latest signed immutable file number or block number in the proof generated by the aggregator
- [x] Verify that the latest signed immutable file number or block number is valid in the client
  - [x] library
  - [x] CLI
  - [x] WASM 
- [ ] Update examples
- [ ] Update documentation
- [ ] Clean stale data in `testing-sanchonet` (e.g. Cardano transactions certificate already signer, ...)

## Related issue
#1561

**Comment by ch1bo** [comment]
FWIW my original request to provide data representing the "recency" of the data on which we verified the transactions. Whether this is a block number, slot number of the corresponding wall-clock time of these does not matter. Why is this needed? To make sense of the outcome, i.e. know whether it's just not "valid yet" and we can hope to verify again later, or (more important) whether the checked txid is invalid (although it should) = maybe someone cheated me (whoever claimed the tx to be valid).

It is _not_ important to me which tx is coming from which block, rather from when the proofs are.

As you mentioned @jpraynaud that timepoint must be signed with the transaction originally and be verifiable by the client code.
