### ISSUE TITLE
Retrieve Cardano blocks with `chainsync` in `pallas` 

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1590]
## Why
We want to retrieve blocks from the Cardano node by using the `chainsync` mini protocol instead of reading the immutable files: this will allow us to get data closer to the tip of the chain (e.g. volatile data). This will also enable Mithril node transactions database warm-up in a background thread.

## What
Create a `PallasBlockReader` that can interact with Cardano `chainsync` mini protocol and implements the draft trait `ChainBlockReader`:
```rust
/// The parsed chain block representation
pub type ParsedBlock = pallas::MultiEraBlock;

/// The action that indicates what to do next when scanning the chain
pub enum ChainBlockNextAction {
    /// RollForward event (we are still on the correct fork)
    RollForward {
        /// The next point in the chain to read
        next_point: ChainPoint,
        /// The parsed block 
        block: ParsedBlock,
    },
    /// RollBackward event (we are on an incorrect fork, we need to get back a point to roll forward again)
    RollBackward {
        /// The rollback point in the chain to read (as a new valid point to read from on the main chain, which has already been seen)
        rollback_point: ChainPoint,
    },
}

/// The trait that reads events to either:
/// - read next block on the chain
/// - rollback to another point in case of rollback
/// - do nothing
pub trait ChainBlockReader {
    //// Get next chain block action
    async fn get_next_chain_block(&self, point: &ChainPoint) -> StdResult<Option<ChainBlockNextAction>>;
}
```

## How

- [x] Add a new `chain_reader` module in `mithril-common`
- [x] Define the trait `ChainBlockReader`
- [x] Implement a `PallasBlockReader` for the `ChainBlockReader` trait
- [x] Implement a `FakeBlockReader` for the `ChainBlockReader` trait (that we can feed with appropriate list of `ChainBlockNext` events)

### See
- https://github.com/txpipe/pallas/blob/97a32c9af5cced098809b5ee4eb72ae0be4cddc2/examples/n2c-miniprotocols/src/main.rs#L84
- Oura: worker thread writing to a queue in the background https://github.com/txpipe/oura/blob/29fed274e8dd46948bccf05ca1ed50705d60adf0/src/sources/n2c.rs#L92
- https://ouroboros-network.cardano.intersectmbo.org/pdfs/network-spec/network-spec.pdf

**Comment by jpraynaud** [comment]
FYI, @falcucci is working on the issue :+1:

**Comment by falcucci** [comment]
@jpraynaud 👍
