### ISSUE TITLE
Preview mithril snapshot download fails due to `certificate hash unmatch error`

### ISSUE THREAD

**Issue by nemo83** [input-output-hk/mithril#1662]
## Context & versions

I'm running mithril client:

```
root@ubuntu:/tmp# /root/mithril-client --version
mithril-client 0.7.6+2e462c0
```

On ubuntu.

As per title, when I attempt to download latest snapthot for `preview` it fails. Mainnet and Preprod are ✅ 

## Steps to reproduce

curl -LO https://github.com/input-output-hk/mithril/releases/download/2412.0/mithril-2412.0-linux-x64.tar.gz
tar xzvf mithril-2412.0-linux-x64.tar.gz
chmod +x mithril-client

explort GENESIS_VERIFICATION_KEY=5b3132372c37332c3132342c3136312c362c3133372c3133312c3231332c3230372c3131372c3139382c38352c3137362c3139392c3136322c3234312c36382c3132332c3131392c3134352c31332c3233322c3234332c34392c3232392c322c3234392c3230352c3230352c33392c3233352c34345d
export AGGREGATOR_ENDPOINT=https://aggregator.pre-release-preview.api.mithril.network/aggregator

/root/mithril-client cardano-db download latest

## Actual behavior

```
root@cardano-node-0:/data# /root/mithril-client cardano-db download ab70c41628c620d2e7d93c70a9dc1fe0d059676a1afd823ffb84b73d46b91901 --download-dir /data/db
1/5 - Checking local disk info…                                                                                                                                                        2/5 - Fetching the certificate and verifying the certificate chain…                                                                                                                    Error: Can not verify the certificate chain from certificate_hash: 'f1415198bd3e2b0874d9260081a84bad4bb2ffee9984f0ccc8fe32320bd49eb5'

Caused by:
    0: Certicate chain of certificate 'f1415198bd3e2b0874d9260081a84bad4bb2ffee9984f0ccc8fe32320bd49eb5' is invalid
    1: certificate hash unmatch error
```

## Expected behavior
Snapshot to be corretly downloaded

**Comment by dlachaume** [comment]
Hello! A breaking change was introduced in the pre-release of Mithril Distribution 241, which impacts the pre-release-preview network.
Your `mithril-client` version is `0.7.6`, please use the latest version of the mithril-client binary, `0.8.0` available [here](https://github.com/input-output-hk/mithril/releases/tag/2418.1-pre).

**Comment by nemo83** [comment]
> Hello! A breaking change was introduced in the pre-release of Mithril Distribution 2418, which impacts the pre-release-preview network. Your `mithril-client` version is `0.7.6`, please use the latest version of the mithril-client binary, `0.8.0` available [here](https://github.com/input-output-hk/mithril/releases/tag/2418.1-pre).

Thanks for coming back to me, as soon as I have a minute will test and let you know!

**Comment by dlachaume** [comment]
Hey @nemo83 👋, did you have time to test it?

**Comment by nemo83** [comment]
Hey, so sorry for the delay.

I just tested it and it works like a charm. Closing.
