### ISSUE TITLE
Resource exhausted on Cardano node socket

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1803]
## Why
The aggregator of the `release-mainnet` network stopped producing certificates and missed in particular the production of the Cardano db snapshot for immutable file number `5917`. After investigation, it appears that the aggregator stopped operating properly as it was unable to retrieve critical information (Tip of the chain) with the local state query mini-protocol: a problem occurred during the connection to the mini-protocol with the error message `Resource temporarily unavailable (os error 11)`. We were able to reproduce the problem with the Cardano cli and received the same error: `<socket: 11>: resource exhausted (Resource temporarily unavailable)`

A restart of the Cardano node was sufficient to reactive the local socket and the aggregator resumed its operations swiftly after the restart.

The Cardano node (`8.9.0`) was up and running for `3` months, and we have never noticed that problem earlier.

## What

Investigate possible cause for the resource exhaustion on the socket.

## How

- [x] Investigate the cause of the error
- [x] Fix the cause of the error #1804

**Comment by jpraynaud** [comment]
Hi @falcucci @scarmuega is this a known issue with Pallas?

**Comment by scarmuega** [comment]
@jpraynaud no, it isn't.

For what I read in the issue, if the error was reproducable through the cardano-cli, this is likely to be an issue with the node instance.

**Comment by jpraynaud** [comment]
> [@jpraynaud](https://github.com/jpraynaud) no, it isn't.
> 
> For what I read in the issue, if the error was reproducable through the cardano-cli, this is likely to be an issue with the node instance.

Thanks for your answer @scarmuega!

I guess the problem is occurring in one of the routes of the REST API of the aggregator instead.

**Comment by jpraynaud** [comment]
Closed with #1804
