### ISSUE TITLE
`ChainReader` is stuck in `Agency is theirs` error

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1836]
## Why
We have noticed that when we are retrieving the blocks from the chain reader at a depth very close to the tip (e.g. in the e2e test), it can get stuck in the following error: `Agency is theirs`. After investigation, we suspect that the problem comes from the call to the `find_intersect_point` function of the `chainsync` mini-protocol in the `set_chain_point` function: this call should be made only when agency is ours in the mini-protocol.

## What
Fix the `ChainReader` implementation so that it does not trigger the error and just make it wait for a new block from the Cardano node (if exists) by shunting the call to the `find_intersect_point` call.

## How

- [x] Investigate the problem
- [ ] Fix the `ChainReader` implementation

**Comment by jpraynaud** [comment]
Hi @falcucci and @scarmuega, can you confirm that the investigation is correct and that the `find_intersect_point` in `chainsync` should not be done when it does not have agency?

**Comment by scarmuega** [comment]
When the client (chain reader in this case) reaches the tip of the chain, the server will send a `AwaitReply` message and the protocol state machine enters the `MustReply` state which holds agency on the server-side.

In simple terms, this means that the client needs to remain idle until the server pushes a new block.

Trying to find a new intersection while the agency is on the server is considered, AFAIK, a protocol violation.

What we usually do on Pallas chain-consumer clients is something like this:

```rust
if client.has_agency() {
    // should request next block
    client.request_next().await?;
} else {
    // should wait until the server sends a block (might be a long wait)
    client.recv_while_must_reply().await?;
}
```

In my experience, finding an intersection point is done once per session at the beginning just to start syncing from where you left of. Everything else is either requesting the next block or waiting for the server to push a block, no need for further intersection actions.

**Comment by jpraynaud** [comment]
Thanks @scarmuega for your help. 
We have fixed the bug 👍
