### ISSUE TITLE
tcp connect error: Connection refused (os error 111)

### ISSUE THREAD

**Issue by BrockCruess** [input-output-hk/mithril#1861]
Seems my signer is suddenly having issues with 0.2.161+6756b0f, not sure if it's related to the version or if something else changed, but nothing has changed with my stake pool aside from upgrading to Cardano Node 9.1.0:

An error occured, runtime state kept. message = 'could not retrieve epoch settings at epoch Epoch(499)'. nested error = remote server unreachable
Caused by:
0: error sending request for url (https://aggregator.release-mainnet.api.mithril.network/aggregator/epoch-settings)
1: client error (Connect)
2: tcp connect error: Connection refused (os error 111)
3: Connection refused (os error 111)

**Comment by jpraynaud** [comment]
Hi @BrockCruess, thanks for creating the issue.

This error means that your Mithril signer node can not access the Mithril aggregator. This is probably due to a mis-configuration of the Mithril relay which does not accept the connection from the signer. 

This may be due to a change of the IP of the machine running the signer: in that case you need to update this line of the relay configuration (` /etc/squid/squid.conf`)  with the correct IP:
```
# ACL for internal IP of your block producer node
acl block_producer_internal_ip src **YOUR_BLOCK_PRODUCER_INTERNAL_IP**
```

**Comment by BrockCruess** [comment]
> ```
> # ACL for internal IP of your block producer node
> acl block_producer_internal_ip src **YOUR_BLOCK_PRODUCER_INTERNAL_IP**
> ```

Adding this line to the Squid config didn't fix it unfortunately, and the block producer's IP is static and has not changed. Nothing in the BP's config has changed, only the Cardano Node version was upgraded.

**Comment by jpraynaud** [comment]
> > ```
> > # ACL for internal IP of your block producer node
> > acl block_producer_internal_ip src **YOUR_BLOCK_PRODUCER_INTERNAL_IP**
> > ```
> 
> Adding this line to the Squid config didn't fix it unfortunately, and the block producer's IP is static and has not changed. Nothing in the BP's config has changed, only the Cardano Node version was upgraded.

Thanks for your answer @BrockCruess.

Can you try to access the aggregator with this command `curl https://aggregator.release-mainnet.api.mithril.network/aggregator/`from:
- your Cardano block producer
- your Cardano relay

Let us know if you can access it or not which will help understanding the problem.
Also, feel free to switch to our Discord channel [ask-mithril](https://discord.gg/5kaErDKDRq) where troubleshooting may be easier.
