### ISSUE TITLE
Add a trend line showing long-term evolution of Cardano DB restorations

### ISSUE THREAD

**Issue by abailly-iohk** [input-output-hk/mithril#1876]
## Why

The [insights](https://lookerstudio.google.com/reporting/8b05ea4b-6a43-45ea-aef2-237906ec7a42/page/kem0D?s=oi6CR5eZrnQ) graphs are awesome, but given the granularity of DB restorations, it's unclear how it's globally faring:

<img width="577" alt="Screenshot 2024-08-01 at 09 39 27" src="https://github.com/user-attachments/assets/4e028ef3-2e88-4343-8d6e-a2a13a9a5000">

## What

Add a line averaging the downloads over a week sliding window to smooth the curve, showing the trend of DB restorations.

**Comment by jpraynaud** [comment]
Hi @abailly-iohk, there is a new line for the moving average of the downloads (done over 30 days) which should give a better idea of the trend of restorations:

![Screenshot from 2024-08-01 11-22-23](https://github.com/user-attachments/assets/89f4bd3f-a6d8-4d9a-9978-4f37da8c5d61)

**Comment by abailly-iohk** [comment]
@jpraynaud that looks great! But it wasn't that urgent :)

**Comment by jpraynaud** [comment]
> @jpraynaud that looks great! But it wasn't that urgent :)

Thanks, that was easy to do :+1:
