### ISSUE TITLE
Optimize memory usage of signer for Cardano transactions

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#1903]
## Why
In order to optimize the **signer memory usage on the SPO infrastructure when signing Cardano transactions**, we need our Merkle tree library to support multiple/custom store implementations optimized for:
- **Proving** in the aggregator: fast but memory intensive (serves both signature and proving)
- **Signing** in the signer: slower but memory optimized (serves only signature)

## What
Implement a Merkle tree store with optimized memory usage in the signer.

## How

- [x] Upgrade the Merkle tree implementation to support multiple stores
- [x] Implement a store for the signer with optimized memory usage based on SQLite
- [x] Benchmark the new signer store
- [ ] Update the signer footprint in documentation

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.
