### ISSUE TITLE
Create a new `/status` route in aggregator

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#2071]
## Why
We need to create a status page on the aggregator that displays basic information which will be used in particular by the explorer.

## What 
Create a `/status` route that displays the aggregator status with the following information:
- Epoch (epoch service)
- Cardano era (epoch service)
- Mithril era (epoch service)
- Cardano node version (static)
- Aggregator version (static)
- Protocol parameters (epoch service)
- Next protocol parameters (epoch service)
- Total signers (epoch service)
- Total next signers (epoch service)
- Total stakes signers (epoch service)
- Total next stakes signers (epoch service)
- Adoption rate (% stake of Cardano in Mithril / % SPOs of Cardano in Mithril)  (epoch service)

## How

- [x] Compute the Cardano era with the chain observer:
  - [x] In the Pallas observer, with the `queries_v16::get_current_era` function and `Era` [type](https://github.com/txpipe/pallas/blob/bda3889b412f19c4e9b0169cef7f41819af6e45a/pallas-traverse/src/era.rs#L23)
  - [x] In the Cardano CLI observer (use the `query tip` command and  read the `era` field)
- [x] Record in epoch service the new information:
  - [x] Cardano era 
  - [x] Mithril era
  - [x] Total SPOs (with `StakeDistributionService`)
  - [x] Total stake (with `StakeDistributionService`)
- [x] Create new `/status` route that displays the status in aggregator
  - [x] Epoch
  - [x] Cardano era
  - [x] Mithril era
  - [x] Cardano node version
  - [x] Aggregator version
  - [x] Protocol parameters
  - [x] Next protocol parameters
  - [x] Total signers
  - [x] Total next signers
  - [x] Total stakes signers
  - [x] #2105
  - [x] Total SPOs in Cardano
  - [x] Total stake in Cardano
- [x] Update OpenAPI specs 
- [ ] Benchmark

## Later
- Latest imported block number
- Latest immutable file number

**Comment by dlachaume** [comment]
## `ab` tests on `testing-preview` after merging the PR https://github.com/input-output-hk/mithril/pull/2107

### Number of requests: 1000

```shell
ab -n 1000 -c 50 https://aggregator.testing-preview.api.mithril.network/aggregator/status
```

- Run 1
```
Requests per second:    313.61 [#/sec] (mean)
Time per request:       159.435 [ms] (mean)
Time per request:       3.189 [ms] (mean, across all concurrent requests)
```

- Run 2
```
Requests per second:    339.47 [#/sec] (mean)
Time per request:       147.290 [ms] (mean)
Time per request:       2.946 [ms] (mean, across all concurrent requests)
```

- Run 3
```
Requests per second:    328.01 [#/sec] (mean)
Time per request:       152.434 [ms] (mean)
Time per request:       3.049 [ms] (mean, across all concurrent requests)
```

### Number of requests: 10 000

```shell
ab -n 10000 -c 50 https://aggregator.testing-preview.api.mithril.network/aggregator/status
```

- Run 1
```
Requests per second:    360.33 [#/sec] (mean)
Time per request:       138.763 [ms] (mean)
Time per request:       2.775 [ms] (mean, across all concurrent requests)
```

- Run 2
```
Requests per second:    359.69 [#/sec] (mean)
Time per request:       139.009 [ms] (mean)
Time per request:       2.780 [ms] (mean, across all concurrent requests)
```

- Run 3
```
Requests per second:    355.45 [#/sec] (mean)
Time per request:       140.667 [ms] (mean)
Time per request:       2.813 [ms] (mean, across all concurrent requests)
```
