### ISSUE TITLE
Snapshot Client can not deserialize artifact list 

### ISSUE THREAD

**Issue by jasagredo** [input-output-hk/mithril#2140]
## Context & versions

I built mithril-client-cli to boostrap a Cardano node, but it fails with an opaque error, and there is no `--verbose` flag that could tell me if I had to delete some cache or something.

## Steps to reproduce

I'm using Windows-MSYS2 in case that matters.

```
❯ git clone git@github.com/input-output-hk/mithril
...
❯ cd mithril/mithril-client-cli
❯ CC=clang make build
...
❯ export CARDANO_NETWORK=mainnet
❯ export AGGREGATOR_ENDPOINT=https://aggregator.release-mainnet.api.mithril.network/aggregator
❯ export GENESIS_VERIFICATION_KEY=$(wget -q -O - https://raw.githubusercontent.com/input-output-hk/mithril/main/mithril-infra/configuration/release-mainnet/genesis.vkey)
❯ ../target/release/mithril-client.exe cardano-db download latest
Error: Can not get the list of artifacts while retrieving the latest cardano db digest

Caused by:
    0: Snapshot Client can not deserialize artifact list
    1: missing field `network` at line 1 column 559
❯ ../target/release/mithril-client.exe cardano-db snapshot list
Error: Snapshot Client can not deserialize artifact list

Caused by:
    missing field `network` at line 1 column 559
❯ ../target/release/mithril-client.exe cardano-db snapshot list --verbose
error: unexpected argument '--verbose' found

Usage: mithril-client.exe cardano-db snapshot list [OPTIONS]

For more information, try '--help'.
```

(mithril-client.exe announces `--verbose` but it doesn't work in the `cardano-db` subcommand).

## Actual behavior

The snapshot client cannot deserialize some artifact, and fails to bootstrap.

**Comment by jpraynaud** [comment]
Hi @jasagredo, thanks for creating the issue.

You are probably running the `unstable` version of the client on the `mainnet` instead of the `latest` released version which you can find [here](https://github.com/input-output-hk/mithril/releases/tag/2445.0).

**Comment by jasagredo** [comment]
That is indeed the case. Thanks @jpraynaud !
