### ISSUE TITLE
Deploy mithril demo infra on 'preview' network

### ISSUE THREAD

**Issue by abailly-iohk** [input-output-hk/mithril#457]
## Why

Current infrastructure is deployed on `testnet` which is soon to be deprecated and is incompatible with newest developments on cardano-node (1.35.3-X series).

## What

* Upgrade `mithril-infra` configuration to deploy over `preprod` network
* Upgrade cardano-node docker to 1.35.3-new

**Comment by SViksha** [comment]
also on PreView

**Comment by abailly-iohk** [comment]
@SViksha We'll do preview first and then preprod

**Comment by jpraynaud** [comment]
The `Mithril Aggregator `hosted on GCP now runs on the `preview` network and has produced its first snapshot :+1: 

To make a `Mithril Signer` work on this network, here is a list of **mandatory** tasks to complete:
1. Recompile the `Mithril Signer` node as explained in this [guide](https://mithril.network/doc/manual/getting-started/run-signer-node/)
2. Use the `NETWORK=preview` environment variable to start the `Mithril Signer` node
3. Wait for `2` epochs before the `Mithril Signer` node starts producing `Individual Signatures`

:warning:  Currently, the `Mithril Signer` node must wait for `~2/3` hours before the `REGISTERED` state is achieved in the state machine. This is normal behavior and the wait delay will be reduced very shortly when #438 will be merged.
