### ISSUE TITLE
Fix CLI args precedence in Client/Signer/Aggregator

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#511]
## Issue
The arguments passed through environment variables in the CLIs are ignored when a default value for a `clap` argument is set.

## Task

- [ ] Fix the precedence order of selection of arguments (or remove default values in `clap`)

**Comment by ghubertpalo** [comment]
In the Client, we shall not have to provide `GENESIS_VERIFICATION_KEY` unless restoring.
