### ISSUE TITLE
SQLite compatibility in aggregator

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#837]
## Issue
We have noticed that the Github Action runners don't have the minimum expected SQLite version:
- We need version `3.40+` for running the queries for the monitoring on the aggregator
- We need version  `3.37+` for everything else in the aggregator
- We have also noticed that the packages that we use to install the version `3.40.1` in the `mithril-infra` has a new location suffixed with `3.40.1-2` when it used to be `3.40.1-1`

## To do 
We need to:
- find a solution that is compatible with the CI (on Linux, Mac OS and Windows) that provides fast enough install time on all the CI runners
- probably implement the same install on the infrastructure
- create a tool sub-command for exporting monitoring data?
- create a tool sub-command for compacting the database?

## Dependencies
Should be done once the tasks `Separate data disk from VM system disk` of #767 is completed

**Comment by Alenar** [comment]
With PR #1024 sqlite is now bundled with our binaries, meaning that we don't need it to be installed on the system anymore and that we can use the latest sqlite version (right now `3.42.0`).

This address most of the issues of this ticket.

Todo:

- [ ] Survey that the bundled sqlite works as intended (ie: do a install on a system/docker without sqlite and check that our nodes works)
- [ ] Update doc websites to remove the install of sqlite as a dependency to install our nodes
- [ ] Update dockerfiles to remove sqlite installation.
