### ISSUE TITLE
Team Meetup

### ISSUE THREAD

**Issue by rezabaram** [input-output-hk/mithril#914]

**Comment by jpraynaud** [comment]
Workshop ideas gathered during Mithril session:
- **Creation of a performance model of Mithril STM library for Leios**: Tooling to prepare a data set usable by researchers 
- **Decentralization**: Design possible scenarios to go decentralized (relay, callbacks/download signatures from aggregator, ...)
- **Signer Incentive**
- **Community**: Pioneer program, animation, ...
- **Mithril/Hydra**: Working together

**Comment by abailly-iohk** [comment]
Perhaps better to fille the meetup's Spreadsheet: https://docs.google.com/spreadsheets/d/1JGlpFqjwS3GQc0Y-CRotTFANFRtHKYEuKi368Aa_yF0/edit#gid=1212195732 ?
