### ISSUE TITLE
Make Cardano node version part of the Mithril network configuration

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#947]
## Issue
The ledger state used to fast bootstrap the Cradano nodes may change from one release of the node to another.
For example, a breaking change was introduced between `1.35.7` and `8.0.0`: this means that a ledger state created with `1.35.7` would need to be recomputed (i.e. replay all blocks) when restored on a node running `8.0.0` (and reciprocally). This does not prevent Cardano nodes to be restored, but it introduces a delay that will limit the speed of restoration.

We want to provide a clear information about which versions of Cardano node are optimum for restoration for each Mithril network.

## To do

- [x] Add a `Cardano node version range` field in the configuration matrix for each network of the documentation
- [x] Add a note/warning in the documentation to explain what happens if the Cardano node version used to restore is not in the range of the Mithril network
- [x] Add the Cardano node version in the command displayed by the Mithril client `download` command (at least in the documentation)

**Comment by ghubertpalo** [comment]
It seems not possible to get the Cardano node version using the Cardano CLI tool (which can just pop out its own version). See this [Stack-Overflow post](https://cardano.stackexchange.com/questions/2357/how-can-check-what-version-of-cardano-node-is-running-on-testnet-or-mainnet).
I will make the assumption the Cardano CLI is the same version as the node.

**Comment by jpraynaud** [comment]
In the documentation the versions are declarative and will be updated manually.

In issue #948, you can assume that the version of the Cardano node is the version given by the Cardano cli with `cardano-cli --version` as they are deployed together.
