### ISSUE TITLE
Clean `pending_snapshot` directory of aggregator

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#983]
## Issue
The `pending_snapshot` directory is never cleaned and some uncompleted snapshots stay forever.
This can create a storage issue (particularly with the `mainnet` archives).

## To do

- [x] Clear `pending_snapshot` before or after snapshot archive is created
- [x] Clear `pending_snapshot` at aggregator startup

**Comment by dlachaumepalo** [comment]
The temp files in the `pending_snapshot` directory were only removed after a successful upload.

Now, `pending_snapshot` directory is cleaned at aggregator startup and uncompleted snapshots archives are removed at every step : 
- if an error occurs during the creation of the archive
- if an error occurs during the upload

More details in the PR https://github.com/input-output-hk/mithril/pull/1011 description.
