### ISSUE TITLE
Add infrastructure monitoring

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#987]
## Issue
Add monitoring (and alerting) of the Mithril infrastructure

## To do
  - [x] Add prometheus endpoint on the Mithril networks (terraform)
  - [x] Gather logs from docker containers with promtail/loki
  - [ ] Configure monitoring/alerting with Grafana Cloud for all Mithril networks (IT Ticket to create)

## Later
  - [ ] Add status dashboard (e.g https://www.githubstatus.com/)?

## Parent issue
#767

**Comment by roynakakawa** [comment]
Questions for Grafana from Procurement: `Can you please advise how many users you will require? The names of those users? Do you expect your monthly usage will be above 100 GB Logs, 100 GB Traces, 20k Metrics?`
