### ISSUE TITLE
Deploy `mainnet` infrastructure

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#988]
## Issue
Deploy the `release-mainnet` network in GCP

## To do
- [x] Setup new `mithril` project in GCP
  - [x] Configure service account
  - [x] Activate services used by the Mithril network
- [x] Configure monitoring/alerting with Grafana Cloud for `release-mainnet` (IT Ticket to create)
- [x] Setup `release-mainnet` network
- [x] Wire `release-mainnet` network in CD workflow
- [x] Update networks matrix in documentation

## Parent Issue
#767

**Comment by roynakakawa** [comment]
Ticket https://input-output.atlassian.net/servicedesk/customer/portal/2/ITCR-6365?created=true
