### ISSUE TITLE
Handle Secrets management

### ISSUE THREAD

**Issue by jpraynaud** [input-output-hk/mithril#989]
## Issue
We need to handle long term storage/security for the cryptographic secrets of the Mithril networks (especially for `mainnet`):
- `Genesis Secret Key`
- `Eras Secret Key`
- `Cardano Era Address Secret Key`

## To do 

- [x] Creation of the secure access for dev team on `VaultWarden` (IT Ticket to create)
- [x] Create and save secret keys in `VaultWarden`
- [x] Create verification keys in Mithril GitHub repository
- [x] Fund `Cardano Era Address Secret Key` with `100` ADA

## Parent Issue
#767

**Comment by roynakakawa** [comment]
Ticket: https://input-output.atlassian.net/servicedesk/customer/portal/2/ITCR-6366?created=true

**Comment by roynakakawa** [comment]
IT grant me with an IOG account in Vaultwarden. @jpraynaud  what should I do with it?
